version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: problem-bank-postgres
    restart: always
    environment:
      POSTGRES_DB: problem-bank
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
