import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import * as schema from '../src/drizzle/schema-math';

// 중1~중3 수학 전체 21개 단원 × 5레벨 × 3문제 = 315문제 생성

async function generateAllMathProblems() {
  const pool = new Pool({
    host: 'localhost',
    port: 5433,
    user: 'user',
    password: 'password',
    database: 'problem-bank',
  });

  const db = drizzle(pool, { schema });

  console.log('🌱 Starting Complete Math Problems Generation...');

  // 1. Math Chapters 생성
  const chaptersData = [
    // 중1 (7단원)
    { gradeLevel: 1, name: '소인수분해', orderIndex: 1 },
    { gradeLevel: 1, name: '정수와 유리수', orderIndex: 2 },
    { gradeLevel: 1, name: '문자와 식', orderIndex: 3 },
    { gradeLevel: 1, name: '일차방정식', orderIndex: 4 },
    { gradeLevel: 1, name: '좌표평면과 그래프', orderIndex: 5 },
    { gradeLevel: 1, name: '통계', orderIndex: 6 },
    { gradeLevel: 1, name: '기본 도형', orderIndex: 7 },

    // 중2 (7단원)
    { gradeLevel: 2, name: '유리수와 순환소수', orderIndex: 1 },
    { gradeLevel: 2, name: '단항식의 계산', orderIndex: 2 },
    { gradeLevel: 2, name: '다항식의 계산', orderIndex: 3 },
    { gradeLevel: 2, name: '일차부등식', orderIndex: 4 },
    { gradeLevel: 2, name: '연립일차방정식', orderIndex: 5 },
    { gradeLevel: 2, name: '일차함수', orderIndex: 6 },
    { gradeLevel: 2, name: '확률', orderIndex: 7 },

    // 중3 (7단원)
    { gradeLevel: 3, name: '제곱근과 실수', orderIndex: 1 },
    { gradeLevel: 3, name: '다항식의 곱셈', orderIndex: 2 },
    { gradeLevel: 3, name: '인수분해', orderIndex: 3 },
    { gradeLevel: 3, name: '이차방정식', orderIndex: 4 },
    { gradeLevel: 3, name: '이차함수', orderIndex: 5 },
    { gradeLevel: 3, name: '삼각비', orderIndex: 6 },
    { gradeLevel: 3, name: '원의 성질', orderIndex: 7 },
  ];

  const chapters = await db
    .insert(schema.mathChapters)
    .values(chaptersData)
    .returning();

  console.log('✅ Math Chapters created:', chapters.length);

  const allProblems: any[] = [];

  // 중1 - 소인수분해
  const ch1 = chapters.find((c) => c.gradeLevel === 1 && c.orderIndex === 1);
  if (ch1) {
    allProblems.push(
      // LEVEL_1
      {
        chapterId: ch1.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: '12를 소인수분해하면?',
        option1: '2² × 3',
        option2: '2 × 6',
        option3: '3 × 4',
        option4: '2 × 3²',
        correctAnswer: '1',
        explanation: '12 = 2 × 6 = 2 × 2 × 3 = 2² × 3',
        tags: '소인수분해,중1수학',
      },
      {
        chapterId: ch1.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: '18의 소인수는?',
        option1: '2, 3',
        option2: '2, 9',
        option3: '3, 6',
        option4: '2, 3, 6',
        correctAnswer: '1',
        explanation: '18 = 2 × 3²이므로 소인수는 2와 3',
        tags: '소인수분해,중1수학',
      },
      {
        chapterId: ch1.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: '24를 소인수분해한 결과는?',
        option1: '2³ × 3',
        option2: '2² × 6',
        option3: '2 × 12',
        option4: '3² × 2',
        correctAnswer: '1',
        explanation: '24 = 2³ × 3',
        tags: '소인수분해,중1수학',
      },
      // LEVEL_2
      {
        chapterId: ch1.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: '72를 소인수분해하면?',
        option1: '2³ × 3²',
        option2: '2² × 3³',
        option3: '2⁴ × 3',
        option4: '2 × 3⁴',
        correctAnswer: '1',
        explanation: '72 = 8 × 9 = 2³ × 3²',
        tags: '소인수분해,중1수학',
      },
      {
        chapterId: ch1.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: '150을 소인수분해하면?',
        option1: '2 × 3 × 5²',
        option2: '2² × 3 × 5',
        option3: '2 × 3² × 5',
        option4: '3 × 5³',
        correctAnswer: '1',
        explanation: '150 = 2 × 3 × 5²',
        tags: '소인수분해,중1수학',
      },
      {
        chapterId: ch1.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: '108의 소인수의 개수는?',
        option1: '2개',
        option2: '3개',
        option3: '4개',
        option4: '5개',
        correctAnswer: '1',
        explanation: '108 = 2² × 3³, 소인수는 2와 3으로 2개',
        tags: '소인수분해,중1수학',
      },
      // LEVEL_3
      {
        chapterId: ch1.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '36과 48의 최대공약수는?',
        option1: '12',
        option2: '6',
        option3: '24',
        option4: '18',
        correctAnswer: '1',
        explanation: '36 = 2² × 3², 48 = 2⁴ × 3, GCD = 2² × 3 = 12',
        tags: '소인수분해,최대공약수,중1수학',
      },
      {
        chapterId: ch1.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '12와 18의 최소공배수는?',
        option1: '36',
        option2: '72',
        option3: '24',
        option4: '216',
        correctAnswer: '1',
        explanation: '12 = 2² × 3, 18 = 2 × 3², LCM = 2² × 3² = 36',
        tags: '소인수분해,최소공배수,중1수학',
      },
      {
        chapterId: ch1.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '2⁴ × 3² × 5를 자연수로 나타내면?',
        option1: '720',
        option2: '360',
        option3: '540',
        option4: '900',
        correctAnswer: '1',
        explanation: '16 × 9 × 5 = 720',
        tags: '소인수분해,중1수학',
      },
      // LEVEL_4
      {
        chapterId: ch1.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: '24, 36, 60의 최대공약수는?',
        option1: '12',
        option2: '6',
        option3: '24',
        option4: '4',
        correctAnswer: '1',
        explanation: 'GCD(24, 36, 60) = 12',
        tags: '소인수분해,최대공약수,중1수학',
      },
      {
        chapterId: ch1.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: '2ⁿ × 3² = 72일 때 n의 값은?',
        option1: '3',
        option2: '2',
        option3: '4',
        option4: '5',
        correctAnswer: '1',
        explanation: '72 = 2³ × 3²이므로 n = 3',
        tags: '소인수분해,중1수학',
      },
      {
        chapterId: ch1.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: '2² × 3 × a가 36의 배수일 때 a의 최솟값은?',
        option1: '3',
        option2: '2',
        option3: '6',
        option4: '9',
        correctAnswer: '1',
        explanation: '36 = 2² × 3²이므로 a = 3',
        tags: '소인수분해,배수,중1수학',
      },
      // LEVEL_5
      {
        chapterId: ch1.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText: '2⁵ × 3³ × 5²의 약수의 개수는?',
        option1: '72개',
        option2: '60개',
        option3: '48개',
        option4: '36개',
        correctAnswer: '1',
        explanation: '(5+1)(3+1)(2+1) = 72개',
        tags: '소인수분해,약수,중1수학',
      },
      {
        chapterId: ch1.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText: '120, 180, 210의 최소공배수는?',
        option1: '1260',
        option2: '2520',
        option3: '3600',
        option4: '5040',
        correctAnswer: '1',
        explanation: 'LCM = 2³ × 3² × 5 × 7 = 1260',
        tags: '소인수분해,최소공배수,중1수학',
      },
      {
        chapterId: ch1.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText: '2ᵃ × 3ᵇ = 216일 때 a + b의 값은?',
        option1: '6',
        option2: '5',
        option3: '7',
        option4: '8',
        correctAnswer: '1',
        explanation: '216 = 2³ × 3³, a + b = 6',
        tags: '소인수분해,중1수학',
      },
    );
  }

  // 중1 - 정수와 유리수
  const ch2 = chapters.find((c) => c.gradeLevel === 1 && c.orderIndex === 2);
  if (ch2) {
    allProblems.push(
      // LEVEL_1
      {
        chapterId: ch2.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: '(-3) + 5의 값은?',
        option1: '2',
        option2: '-2',
        option3: '8',
        option4: '-8',
        correctAnswer: '1',
        explanation: '-3 + 5 = 2',
        tags: '정수,덧셈,중1수학',
      },
      {
        chapterId: ch2.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: '7 - 10의 값은?',
        option1: '-3',
        option2: '3',
        option3: '-17',
        option4: '17',
        correctAnswer: '1',
        explanation: '7 - 10 = -3',
        tags: '정수,뺄셈,중1수학',
      },
      {
        chapterId: ch2.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: '(-4) × 3의 값은?',
        option1: '-12',
        option2: '12',
        option3: '-7',
        option4: '7',
        correctAnswer: '1',
        explanation: '(-4) × 3 = -12',
        tags: '정수,곱셈,중1수학',
      },
      // LEVEL_2
      {
        chapterId: ch2.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: '(-6) ÷ 2의 값은?',
        option1: '-3',
        option2: '3',
        option3: '-4',
        option4: '4',
        correctAnswer: '1',
        explanation: '(-6) ÷ 2 = -3',
        tags: '정수,나눗셈,중1수학',
      },
      {
        chapterId: ch2.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: '(-2) × (-5)의 값은?',
        option1: '10',
        option2: '-10',
        option3: '7',
        option4: '-7',
        correctAnswer: '1',
        explanation: '음수 × 음수 = 양수, 10',
        tags: '정수,곱셈,중1수학',
      },
      {
        chapterId: ch2.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: '1/2 + 1/3의 값은?',
        option1: '5/6',
        option2: '2/5',
        option3: '1/6',
        option4: '3/6',
        correctAnswer: '1',
        explanation: '3/6 + 2/6 = 5/6',
        tags: '유리수,분수,중1수학',
      },
      // LEVEL_3
      {
        chapterId: ch2.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '(-3) + 7 - 5의 값은?',
        option1: '-1',
        option2: '1',
        option3: '9',
        option4: '-9',
        correctAnswer: '1',
        explanation: '4 - 5 = -1',
        tags: '정수,사칙연산,중1수학',
      },
      {
        chapterId: ch2.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '2/3 - 1/4의 값은?',
        option1: '5/12',
        option2: '1/12',
        option3: '7/12',
        option4: '1/7',
        correctAnswer: '1',
        explanation: '8/12 - 3/12 = 5/12',
        tags: '유리수,분수,중1수학',
      },
      {
        chapterId: ch2.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '(-2)³의 값은?',
        option1: '-8',
        option2: '8',
        option3: '-6',
        option4: '6',
        correctAnswer: '1',
        explanation: '(-2)³ = -8',
        tags: '정수,거듭제곱,중1수학',
      },
      // LEVEL_4
      {
        chapterId: ch2.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: '(-1) × 2 - 3 × (-4)의 값은?',
        option1: '10',
        option2: '-10',
        option3: '14',
        option4: '-14',
        correctAnswer: '1',
        explanation: '-2 + 12 = 10',
        tags: '정수,사칙연산,중1수학',
      },
      {
        chapterId: ch2.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: '2/5 × 3/4의 값은?',
        option1: '3/10',
        option2: '6/20',
        option3: '5/9',
        option4: '1/2',
        correctAnswer: '1',
        explanation: '6/20 = 3/10',
        tags: '유리수,분수,중1수학',
      },
      {
        chapterId: ch2.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: '(-2)² + (-3)²의 값은?',
        option1: '13',
        option2: '-13',
        option3: '5',
        option4: '-5',
        correctAnswer: '1',
        explanation: '4 + 9 = 13',
        tags: '정수,거듭제곱,중1수학',
      },
      // LEVEL_5
      {
        chapterId: ch2.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText: '(-2)³ × 3 + 5 × (-4)의 값은?',
        option1: '-44',
        option2: '44',
        option3: '-20',
        option4: '20',
        correctAnswer: '1',
        explanation: '-24 - 20 = -44',
        tags: '정수,복합연산,중1수학',
      },
      {
        chapterId: ch2.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText: '(2/3 + 1/6) × 3의 값은?',
        option1: '5/2',
        option2: '3/2',
        option3: '7/2',
        option4: '1',
        correctAnswer: '1',
        explanation: '5/6 × 3 = 5/2',
        tags: '유리수,복합연산,중1수학',
      },
      {
        chapterId: ch2.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText: '1 ÷ (1/2 - 1/3)의 값은?',
        option1: '6',
        option2: '3',
        option3: '12',
        option4: '1/6',
        correctAnswer: '1',
        explanation: '1 ÷ 1/6 = 6',
        tags: '유리수,나눗셈,중1수학',
      },
    );
  }

  // 중1 - 문자와 식 (15문제)
  const ch3 = chapters.find((c) => c.gradeLevel === 1 && c.orderIndex === 3);
  if (ch3) {
    allProblems.push(
      // LEVEL_1
      {
        chapterId: ch3.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: '3x + 2x를 간단히 하면?',
        option1: '5x',
        option2: '6x',
        option3: '5x²',
        option4: 'x⁵',
        correctAnswer: '1',
        explanation: '동류항: 3x + 2x = 5x',
        tags: '문자와식,중1수학',
      },
      {
        chapterId: ch3.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: '7a - 3a의 값은?',
        option1: '4a',
        option2: '10a',
        option3: '4',
        option4: '10',
        correctAnswer: '1',
        explanation: '7a - 3a = 4a',
        tags: '문자와식,중1수학',
      },
      {
        chapterId: ch3.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: '2 × x를 간단히 나타내면?',
        option1: '2x',
        option2: 'x2',
        option3: '2 + x',
        option4: 'x/2',
        correctAnswer: '1',
        explanation: '2x (곱셈 기호 생략)',
        tags: '문자와식,중1수학',
      },
      // LEVEL_2
      {
        chapterId: ch3.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: '5x + 3y - 2x + y를 간단히 하면?',
        option1: '3x + 4y',
        option2: '7x + 2y',
        option3: '3x + 2y',
        option4: '5x + 4y',
        correctAnswer: '1',
        explanation: '(5x - 2x) + (3y + y) = 3x + 4y',
        tags: '문자와식,중1수학',
      },
      {
        chapterId: ch3.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: '3(x + 2)를 전개하면?',
        option1: '3x + 6',
        option2: '3x + 2',
        option3: 'x + 6',
        option4: '3x + 5',
        correctAnswer: '1',
        explanation: '3x + 6',
        tags: '문자와식,전개,중1수학',
      },
      {
        chapterId: ch3.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: '2x × 3y를 간단히 하면?',
        option1: '6xy',
        option2: '5xy',
        option3: '6x + y',
        option4: '2x + 3y',
        correctAnswer: '1',
        explanation: '2 × 3 × x × y = 6xy',
        tags: '문자와식,곱셈,중1수학',
      },
      // LEVEL_3
      {
        chapterId: ch3.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '4(x - 1) + 2(x + 3)을 간단히 하면?',
        option1: '6x + 2',
        option2: '6x - 4',
        option3: '6x + 6',
        option4: '4x + 2',
        correctAnswer: '1',
        explanation: '4x - 4 + 2x + 6 = 6x + 2',
        tags: '문자와식,전개,중1수학',
      },
      {
        chapterId: ch3.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '12xy ÷ 3x를 간단히 하면?',
        option1: '4y',
        option2: '9y',
        option3: '4xy',
        option4: '15xy',
        correctAnswer: '1',
        explanation: '12xy ÷ 3x = 4y',
        tags: '문자와식,나눗셈,중1수학',
      },
      {
        chapterId: ch3.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: 'x = 2일 때 3x - 5의 값은?',
        option1: '1',
        option2: '6',
        option3: '11',
        option4: '-1',
        correctAnswer: '1',
        explanation: '3(2) - 5 = 1',
        tags: '문자와식,대입,중1수학',
      },
      // LEVEL_4
      {
        chapterId: ch3.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: '3(2x - y) - 2(x + 3y)를 간단히 하면?',
        option1: '4x - 9y',
        option2: '4x - 3y',
        option3: '6x - 9y',
        option4: '4x + 3y',
        correctAnswer: '1',
        explanation: '6x - 3y - 2x - 6y = 4x - 9y',
        tags: '문자와식,전개,중1수학',
      },
      {
        chapterId: ch3.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: 'x = -2, y = 3일 때 2x + 3y의 값은?',
        option1: '5',
        option2: '-5',
        option3: '13',
        option4: '1',
        correctAnswer: '1',
        explanation: '2(-2) + 3(3) = -4 + 9 = 5',
        tags: '문자와식,대입,중1수학',
      },
      {
        chapterId: ch3.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: '15a²b ÷ 5ab를 간단히 하면?',
        option1: '3a',
        option2: '3b',
        option3: '3ab',
        option4: '10a',
        correctAnswer: '1',
        explanation: '15a²b ÷ 5ab = 3a',
        tags: '문자와식,나눗셈,중1수학',
      },
      // LEVEL_5
      {
        chapterId: ch3.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText: '2(x - 3y) - 3(2x - y) + 4(x + y)를 간단히 하면?',
        option1: '1',
        option2: '2x',
        option3: '2y',
        option4: '0',
        correctAnswer: '1',
        explanation: '2x - 6y - 6x + 3y + 4x + 4y = y',
        tags: '문자와식,복합전개,중1수학',
      },
      {
        chapterId: ch3.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText: 'x = 1/2일 때 4x² - 2x + 1의 값은?',
        option1: '1',
        option2: '0',
        option3: '2',
        option4: '1/2',
        correctAnswer: '1',
        explanation: '4(1/4) - 1 + 1 = 1',
        tags: '문자와식,대입,중1수학',
      },
      {
        chapterId: ch3.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText: '(-2ab)³을 간단히 하면?',
        option1: '-8a³b³',
        option2: '8a³b³',
        option3: '-6a³b³',
        option4: '-8ab³',
        correctAnswer: '1',
        explanation: '(-2)³a³b³ = -8a³b³',
        tags: '문자와식,거듭제곱,중1수학',
      },
    );
  }

  // 중1 - 일차방정식 (ch4)
  const ch4 = chapters.find((c) => c.gradeLevel === 1 && c.orderIndex === 4);
  if (ch4) {
    allProblems.push(
      // LEVEL_1
      {
        chapterId: ch4.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: 'x + 3 = 7을 풀면?',
        option1: 'x = 4',
        option2: 'x = 10',
        option3: 'x = 3',
        option4: 'x = -4',
        correctAnswer: '1',
        explanation: 'x = 7 - 3 = 4',
        tags: '일차방정식,중1수학',
      },
      {
        chapterId: ch4.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: 'x - 5 = 2를 풀면?',
        option1: 'x = 7',
        option2: 'x = -3',
        option3: 'x = 3',
        option4: 'x = -7',
        correctAnswer: '1',
        explanation: 'x = 2 + 5 = 7',
        tags: '일차방정식,중1수학',
      },
      {
        chapterId: ch4.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: '2x = 10을 풀면?',
        option1: 'x = 5',
        option2: 'x = 20',
        option3: 'x = 8',
        option4: 'x = 12',
        correctAnswer: '1',
        explanation: 'x = 10 ÷ 2 = 5',
        tags: '일차방정식,중1수학',
      },
      // LEVEL_2
      {
        chapterId: ch4.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: '2x + 3 = 11을 풀면?',
        option1: 'x = 4',
        option2: 'x = 7',
        option3: 'x = 14',
        option4: 'x = 8',
        correctAnswer: '1',
        explanation: '2x = 8, x = 4',
        tags: '일차방정식,중1수학',
      },
      {
        chapterId: ch4.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: '3x - 5 = 10을 풀면?',
        option1: 'x = 5',
        option2: 'x = 15',
        option3: 'x = 3',
        option4: 'x = 2',
        correctAnswer: '1',
        explanation: '3x = 15, x = 5',
        tags: '일차방정식,중1수학',
      },
      {
        chapterId: ch4.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: 'x/2 = 6을 풀면?',
        option1: 'x = 12',
        option2: 'x = 3',
        option3: 'x = 8',
        option4: 'x = 4',
        correctAnswer: '1',
        explanation: 'x = 6 × 2 = 12',
        tags: '일차방정식,중1수학',
      },
      // LEVEL_3
      {
        chapterId: ch4.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '4x - 7 = 2x + 5를 풀면?',
        option1: 'x = 6',
        option2: 'x = 12',
        option3: 'x = -1',
        option4: 'x = 3',
        correctAnswer: '1',
        explanation: '2x = 12, x = 6',
        tags: '일차방정식,중1수학',
      },
      {
        chapterId: ch4.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '5(x - 2) = 15를 풀면?',
        option1: 'x = 5',
        option2: 'x = 3',
        option3: 'x = 7',
        option4: 'x = 13',
        correctAnswer: '1',
        explanation: 'x - 2 = 3, x = 5',
        tags: '일차방정식,중1수학',
      },
      {
        chapterId: ch4.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '2(x + 3) = 3x - 1을 풀면?',
        option1: 'x = 7',
        option2: 'x = 5',
        option3: 'x = 1',
        option4: 'x = -7',
        correctAnswer: '1',
        explanation: '2x + 6 = 3x - 1, x = 7',
        tags: '일차방정식,중1수학',
      },
      // LEVEL_4
      {
        chapterId: ch4.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: '3(2x - 1) = 2(x + 5)를 풀면?',
        option1: 'x = 13/4',
        option2: 'x = 4',
        option3: 'x = 3',
        option4: 'x = 2',
        correctAnswer: '1',
        explanation: '6x - 3 = 2x + 10, 4x = 13, x = 13/4',
        tags: '일차방정식,중1수학',
      },
      {
        chapterId: ch4.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: '0.5x + 1.5 = 3을 풀면?',
        option1: 'x = 3',
        option2: 'x = 9',
        option3: 'x = 1',
        option4: 'x = 4.5',
        correctAnswer: '1',
        explanation: '0.5x = 1.5, x = 3',
        tags: '일차방정식,소수,중1수학',
      },
      {
        chapterId: ch4.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: 'x/3 + x/2 = 5를 풀면?',
        option1: 'x = 6',
        option2: 'x = 15',
        option3: 'x = 10',
        option4: 'x = 30',
        correctAnswer: '1',
        explanation: '2x + 3x = 30, 5x = 30, x = 6',
        tags: '일차방정식,분수,중1수학',
      },
      // LEVEL_5
      {
        chapterId: ch4.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText: '(x-1)/2 - (x+2)/3 = 1을 풀면?',
        option1: 'x = -13',
        option2: 'x = 13',
        option3: 'x = -7',
        option4: 'x = 7',
        correctAnswer: '1',
        explanation: '3(x-1) - 2(x+2) = 6, x = -13',
        tags: '일차방정식,복합분수,중1수학',
      },
      {
        chapterId: ch4.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText: '2(x-3) - 3(2x-1) = 5를 풀면?',
        option1: 'x = -2',
        option2: 'x = 2',
        option3: 'x = 8',
        option4: 'x = -8',
        correctAnswer: '1',
        explanation: '2x - 6 - 6x + 3 = 5, -4x = 8, x = -2',
        tags: '일차방정식,복합,중1수학',
      },
      {
        chapterId: ch4.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText: '0.3x + 0.7 = 0.2x + 1.2를 풀면?',
        option1: 'x = 5',
        option2: 'x = 2',
        option3: 'x = 10',
        option4: 'x = 1',
        correctAnswer: '1',
        explanation: '0.1x = 0.5, x = 5',
        tags: '일차방정식,소수,중1수학',
      },
    );
  }

  // 중1 - 좌표평면과 그래프 (ch5) - 15문제
  const ch5 = chapters.find((c) => c.gradeLevel === 1 && c.orderIndex === 5);
  if (ch5) {
    allProblems.push(
      {
        chapterId: ch5.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: '점 (3, 2)의 x좌표는?',
        option1: '3',
        option2: '2',
        option3: '5',
        option4: '1',
        correctAnswer: '1',
        explanation: 'x좌표는 3',
        tags: '좌표,중1수학',
      },
      {
        chapterId: ch5.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: '점 (-2, 4)의 y좌표는?',
        option1: '4',
        option2: '-2',
        option3: '2',
        option4: '-4',
        correctAnswer: '1',
        explanation: 'y좌표는 4',
        tags: '좌표,중1수학',
      },
      {
        chapterId: ch5.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: '원점의 좌표는?',
        option1: '(0, 0)',
        option2: '(1, 1)',
        option3: '(0, 1)',
        option4: '(1, 0)',
        correctAnswer: '1',
        explanation: '원점은 (0, 0)',
        tags: '좌표,중1수학',
      },
      {
        chapterId: ch5.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: '점 (2, -3)은 제 몇 사분면?',
        option1: '제4사분면',
        option2: '제1사분면',
        option3: '제2사분면',
        option4: '제3사분면',
        correctAnswer: '1',
        explanation: 'x > 0, y < 0이므로 제4사분면',
        tags: '좌표,사분면,중1수학',
      },
      {
        chapterId: ch5.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: '점 (-3, 5)는 제 몇 사분면?',
        option1: '제2사분면',
        option2: '제1사분면',
        option3: '제3사분면',
        option4: '제4사분면',
        correctAnswer: '1',
        explanation: 'x < 0, y > 0이므로 제2사분면',
        tags: '좌표,사분면,중1수학',
      },
      {
        chapterId: ch5.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: 'x축 위의 점의 y좌표는?',
        option1: '0',
        option2: '1',
        option3: 'x',
        option4: '임의의 값',
        correctAnswer: '1',
        explanation: 'x축 위의 점은 y = 0',
        tags: '좌표,축,중1수학',
      },
      {
        chapterId: ch5.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '두 점 (1, 2)와 (4, 2)를 지나는 직선은 x축에 대해?',
        option1: '평행하다',
        option2: '수직이다',
        option3: '일치한다',
        option4: '비스듬하다',
        correctAnswer: '1',
        explanation: 'y좌표가 같으므로 x축에 평행',
        tags: '좌표,직선,중1수학',
      },
      {
        chapterId: ch5.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '점 (a, -3)이 제4사분면에 있을 때 a의 범위는?',
        option1: 'a > 0',
        option2: 'a < 0',
        option3: 'a = 0',
        option4: 'a ≠ 0',
        correctAnswer: '1',
        explanation: '제4사분면은 x > 0, y < 0',
        tags: '좌표,사분면,중1수학',
      },
      {
        chapterId: ch5.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '점 (3, 0)은 어디에 위치?',
        option1: 'x축 위',
        option2: 'y축 위',
        option3: '제1사분면',
        option4: '제4사분면',
        correctAnswer: '1',
        explanation: 'y = 0이므로 x축 위',
        tags: '좌표,축,중1수학',
      },
      {
        chapterId: ch5.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: '점 (2, 3)을 x축에 대해 대칭이동하면?',
        option1: '(2, -3)',
        option2: '(-2, 3)',
        option3: '(-2, -3)',
        option4: '(3, 2)',
        correctAnswer: '1',
        explanation: 'x축 대칭: x좌표 그대로, y좌표 부호 반대',
        tags: '좌표,대칭,중1수학',
      },
      {
        chapterId: ch5.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: '점 (-3, 5)를 y축에 대해 대칭이동하면?',
        option1: '(3, 5)',
        option2: '(-3, -5)',
        option3: '(3, -5)',
        option4: '(5, -3)',
        correctAnswer: '1',
        explanation: 'y축 대칭: x좌표 부호 반대, y좌표 그대로',
        tags: '좌표,대칭,중1수학',
      },
      {
        chapterId: ch5.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText:
          '두 점 (1, 2), (3, y)를 잇는 선분의 중점이 (2, 4)일 때 y는?',
        option1: '6',
        option2: '4',
        option3: '2',
        option4: '8',
        correctAnswer: '1',
        explanation: '(2 + y)/2 = 4, y = 6',
        tags: '좌표,중점,중1수학',
      },
      {
        chapterId: ch5.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText: '점 (a, b)를 원점에 대해 대칭이동하면?',
        option1: '(-a, -b)',
        option2: '(a, -b)',
        option3: '(-a, b)',
        option4: '(b, a)',
        correctAnswer: '1',
        explanation: '원점 대칭: 양쪽 좌표 부호 반대',
        tags: '좌표,대칭,중1수학',
      },
      {
        chapterId: ch5.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText:
          '세 점 A(1,2), B(4,6), C(x,y)가 일직선상, AB=BC일 때 C의 좌표는?',
        option1: '(7, 10)',
        option2: '(5, 8)',
        option3: '(3, 4)',
        option4: '(6, 9)',
        correctAnswer: '1',
        explanation: 'C = (7, 10)',
        tags: '좌표,직선,중1수학',
      },
      {
        chapterId: ch5.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText:
          '네 점 (0,0), (3,0), (3,4), (0,4)를 꼭짓점으로 하는 도형의 넓이는?',
        option1: '12',
        option2: '14',
        option3: '10',
        option4: '16',
        correctAnswer: '1',
        explanation: '직사각형: 3 × 4 = 12',
        tags: '좌표,도형,중1수학',
      },
    );
  }

  // 중1 - 통계 (ch6) - 15문제
  const ch6 = chapters.find((c) => c.gradeLevel === 1 && c.orderIndex === 6);
  if (ch6) {
    allProblems.push(
      {
        chapterId: ch6.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: '자료 3, 5, 7의 평균은?',
        option1: '5',
        option2: '15',
        option3: '6',
        option4: '4',
        correctAnswer: '1',
        explanation: '(3+5+7)/3 = 5',
        tags: '통계,평균,중1수학',
      },
      {
        chapterId: ch6.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: '자료 2, 4, 6, 8의 평균은?',
        option1: '5',
        option2: '20',
        option3: '4',
        option4: '6',
        correctAnswer: '1',
        explanation: '(2+4+6+8)/4 = 5',
        tags: '통계,평균,중1수학',
      },
      {
        chapterId: ch6.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: '자료 1, 2, 3, 4, 5의 중앙값은?',
        option1: '3',
        option2: '2',
        option3: '4',
        option4: '5',
        correctAnswer: '1',
        explanation: '가운데 값 = 3',
        tags: '통계,중앙값,중1수학',
      },
      {
        chapterId: ch6.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: '자료 3, 5, 5, 7, 10의 최빈값은?',
        option1: '5',
        option2: '6',
        option3: '7',
        option4: '3',
        correctAnswer: '1',
        explanation: '가장 많이 나타난 값 = 5',
        tags: '통계,최빈값,중1수학',
      },
      {
        chapterId: ch6.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: '자료 10, 20, 30, 40의 평균과 중앙값의 합은?',
        option1: '50',
        option2: '25',
        option3: '75',
        option4: '100',
        correctAnswer: '1',
        explanation: '평균 25, 중앙값 25, 합 50',
        tags: '통계,중1수학',
      },
      {
        chapterId: ch6.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: '자료 2, 4, 6, 8, 10의 범위는?',
        option1: '8',
        option2: '6',
        option3: '10',
        option4: '2',
        correctAnswer: '1',
        explanation: '최댓값 - 최솟값 = 10 - 2 = 8',
        tags: '통계,범위,중1수학',
      },
      {
        chapterId: ch6.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '5개 자료의 평균이 10일 때 자료의 총합은?',
        option1: '50',
        option2: '10',
        option3: '15',
        option4: '5',
        correctAnswer: '1',
        explanation: '평균 × 개수 = 10 × 5 = 50',
        tags: '통계,평균,중1수학',
      },
      {
        chapterId: ch6.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '자료 2, 5, 7, 8, x의 평균이 6일 때 x는?',
        option1: '8',
        option2: '6',
        option3: '10',
        option4: '4',
        correctAnswer: '1',
        explanation: '(22 + x)/5 = 6, x = 8',
        tags: '통계,평균,중1수학',
      },
      {
        chapterId: ch6.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '자료 1, 3, 5, 7, 9의 분산은?',
        option1: '8',
        option2: '5',
        option3: '25',
        option4: '10',
        correctAnswer: '1',
        explanation: '평균 5, 분산 = (16+4+0+4+16)/5 = 8',
        tags: '통계,분산,중1수학',
      },
      {
        chapterId: ch6.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: '자료 2, 4, 6, 8, 10의 표준편차는?',
        option1: '2√2',
        option2: '8',
        option3: '4',
        option4: '2',
        correctAnswer: '1',
        explanation: '분산 8, 표준편차 = √8 = 2√2',
        tags: '통계,표준편차,중1수학',
      },
      {
        chapterId: ch6.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: '평균 5, 분산 4인 자료에 모두 3을 더하면 새 평균은?',
        option1: '8',
        option2: '5',
        option3: '7',
        option4: '9',
        correctAnswer: '1',
        explanation: '평균 + 3 = 5 + 3 = 8',
        tags: '통계,평균,중1수학',
      },
      {
        chapterId: ch6.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: '평균 10인 자료에 모두 2를 곱하면 새 평균은?',
        option1: '20',
        option2: '10',
        option3: '12',
        option4: '5',
        correctAnswer: '1',
        explanation: '평균 × 2 = 10 × 2 = 20',
        tags: '통계,평균,중1수학',
      },
      {
        chapterId: ch6.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText: '평균 50, 분산 100인 자료에 모두 10을 빼면 새 분산은?',
        option1: '100',
        option2: '90',
        option3: '110',
        option4: '40',
        correctAnswer: '1',
        explanation: '분산은 변하지 않음',
        tags: '통계,분산,중1수학',
      },
      {
        chapterId: ch6.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText:
          '자료 A 평균50 표준편차10, 자료 B 평균40 표준편차5. 어느 자료가 더 흩어져 있는가?',
        option1: 'A',
        option2: 'B',
        option3: '같다',
        option4: '알 수 없다',
        correctAnswer: '1',
        explanation: 'A의 표준편차가 더 크므로 더 흩어짐',
        tags: '통계,표준편차,중1수학',
      },
      {
        chapterId: ch6.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText: '평균 a, 분산 b²인 자료에 모두 k를 곱하면 새 분산은?',
        option1: 'k²b²',
        option2: 'kb²',
        option3: 'b²',
        option4: 'k²b',
        correctAnswer: '1',
        explanation: '분산은 k²배',
        tags: '통계,분산,중1수학',
      },
    );
  }

  // 중1 - 기본 도형 (ch7) - 15문제
  const ch7 = chapters.find((c) => c.gradeLevel === 1 && c.orderIndex === 7);
  if (ch7) {
    allProblems.push(
      {
        chapterId: ch7.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: '180°의 각은?',
        option1: '평각',
        option2: '직각',
        option3: '예각',
        option4: '둔각',
        correctAnswer: '1',
        explanation: '180° = 평각',
        tags: '도형,각,중1수학',
      },
      {
        chapterId: ch7.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: '90°의 각은?',
        option1: '직각',
        option2: '평각',
        option3: '예각',
        option4: '둔각',
        correctAnswer: '1',
        explanation: '90° = 직각',
        tags: '도형,각,중1수학',
      },
      {
        chapterId: ch7.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_1',
        questionText: '두 직선이 만나서 이루는 대각의 크기는?',
        option1: '같다',
        option2: '다르다',
        option3: '합이 180°',
        option4: '합이 90°',
        correctAnswer: '1',
        explanation: '대각은 크기가 같다',
        tags: '도형,각,중1수학',
      },
      {
        chapterId: ch7.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: '보각이 120°인 각의 크기는?',
        option1: '60°',
        option2: '120°',
        option3: '30°',
        option4: '90°',
        correctAnswer: '1',
        explanation: '180° - 120° = 60°',
        tags: '도형,각,중1수학',
      },
      {
        chapterId: ch7.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: '여각이 40°인 각의 크기는?',
        option1: '50°',
        option2: '40°',
        option3: '140°',
        option4: '90°',
        correctAnswer: '1',
        explanation: '90° - 40° = 50°',
        tags: '도형,각,중1수학',
      },
      {
        chapterId: ch7.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_2',
        questionText: '삼각형의 내각의 합은?',
        option1: '180°',
        option2: '360°',
        option3: '90°',
        option4: '270°',
        correctAnswer: '1',
        explanation: '삼각형 내각의 합 = 180°',
        tags: '도형,삼각형,중1수학',
      },
      {
        chapterId: ch7.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '정삼각형의 한 내각의 크기는?',
        option1: '60°',
        option2: '90°',
        option3: '120°',
        option4: '45°',
        correctAnswer: '1',
        explanation: '180° ÷ 3 = 60°',
        tags: '도형,정삼각형,중1수학',
      },
      {
        chapterId: ch7.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '이등변삼각형에서 꼭지각이 80°일 때 밑각은?',
        option1: '50°',
        option2: '100°',
        option3: '40°',
        option4: '80°',
        correctAnswer: '1',
        explanation: '(180° - 80°) ÷ 2 = 50°',
        tags: '도형,이등변삼각형,중1수학',
      },
      {
        chapterId: ch7.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_3',
        questionText: '삼각형에서 한 외각의 크기는?',
        option1: '이웃하지 않은 두 내각의 합',
        option2: '이웃한 내각의 합',
        option3: '모든 내각의 합',
        option4: '한 내각의 2배',
        correctAnswer: '1',
        explanation: '외각 = 이웃하지 않은 두 내각의 합',
        tags: '도형,삼각형,중1수학',
      },
      {
        chapterId: ch7.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: '오각형의 내각의 합은?',
        option1: '540°',
        option2: '360°',
        option3: '720°',
        option4: '900°',
        correctAnswer: '1',
        explanation: '(5-2) × 180° = 540°',
        tags: '도형,다각형,중1수학',
      },
      {
        chapterId: ch7.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: '정육각형의 한 내각의 크기는?',
        option1: '120°',
        option2: '60°',
        option3: '90°',
        option4: '108°',
        correctAnswer: '1',
        explanation: '(6-2) × 180° ÷ 6 = 120°',
        tags: '도형,정다각형,중1수학',
      },
      {
        chapterId: ch7.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_4',
        questionText: '다각형의 외각의 합은?',
        option1: '360°',
        option2: '180°',
        option3: '540°',
        option4: '720°',
        correctAnswer: '1',
        explanation: '모든 다각형의 외각의 합 = 360°',
        tags: '도형,다각형,중1수학',
      },
      {
        chapterId: ch7.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText: '정n각형의 한 내각이 140°일 때 n은?',
        option1: '9',
        option2: '8',
        option3: '10',
        option4: '7',
        correctAnswer: '1',
        explanation: '한 외각 = 40°, n = 360°/40° = 9',
        tags: '도형,정다각형,중1수학',
      },
      {
        chapterId: ch7.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText: '대각선의 개수가 20개인 다각형의 변의 개수는?',
        option1: '8',
        option2: '7',
        option3: '9',
        option4: '10',
        correctAnswer: '1',
        explanation: 'n(n-3)/2 = 20, n = 8',
        tags: '도형,다각형,중1수학',
      },
      {
        chapterId: ch7.id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'LEVEL_5',
        questionText: '한 내각이 150°인 정다각형의 변의 개수는?',
        option1: '12',
        option2: '10',
        option3: '15',
        option4: '18',
        correctAnswer: '1',
        explanation: '한 외각 = 30°, n = 360°/30° = 12',
        tags: '도형,정다각형,중1수학',
      },
    );
  }

  console.log('✅ Math Problems prepared:', allProblems.length);

  if (allProblems.length > 0) {
    const problems = await db
      .insert(schema.mathProblems)
      .values(allProblems)
      .returning();

    console.log('✅ Math Problems inserted:', problems.length);
  }

  await pool.end();
  console.log('🎉 Math Problems Generation completed!');
}

generateAllMathProblems().catch(console.error);
