import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import * as schema from '../src/drizzle/schema';

async function seed() {
  const pool = new Pool({
    host: 'localhost',
    port: 5433,
    user: 'user',
    password: 'password',
    database: 'problem-bank',
  });

  const db = drizzle(pool, { schema });

  console.log('🌱 Starting seed...');

  // 1. Subjects 생성
  const subjects = await db
    .insert(schema.subjects)
    .values([
      { name: '수학', description: '중학교 수학 문제은행' },
      { name: '영어', description: '중학교 영어 문제은행' },
    ])
    .returning();

  console.log('✅ Subjects created:', subjects.length);

  // 2. Grades 생성 (수학 중1, 중2, 중3 + 영어 중1, 중2, 중3)
  const grades = await db
    .insert(schema.grades)
    .values([
      // 수학 학년
      {
        subjectId: subjects[0].id,
        name: '중1',
        displayOrder: 1,
        schoolLevel: 'MIDDLE',
      },
      {
        subjectId: subjects[0].id,
        name: '중2',
        displayOrder: 2,
        schoolLevel: 'MIDDLE',
      },
      {
        subjectId: subjects[0].id,
        name: '중3',
        displayOrder: 3,
        schoolLevel: 'MIDDLE',
      },
      // 영어 학년
      {
        subjectId: subjects[1].id,
        name: '중1',
        displayOrder: 1,
        schoolLevel: 'MIDDLE',
      },
      {
        subjectId: subjects[1].id,
        name: '중2',
        displayOrder: 2,
        schoolLevel: 'MIDDLE',
      },
      {
        subjectId: subjects[1].id,
        name: '중3',
        displayOrder: 3,
        schoolLevel: 'MIDDLE',
      },
    ])
    .returning();

  console.log('✅ Grades created:', grades.length);

  // 3. Chapters 생성 (학년별 실제 단원)
  const chapters = await db
    .insert(schema.chapters)
    .values([
      // 중1 단원 (7개)
      {
        subjectId: subjects[0].id,
        gradeId: grades[0].id,
        name: '소인수분해',
        orderIndex: 1,
      },
      {
        subjectId: subjects[0].id,
        gradeId: grades[0].id,
        name: '정수와 유리수',
        orderIndex: 2,
      },
      {
        subjectId: subjects[0].id,
        gradeId: grades[0].id,
        name: '문자와 식',
        orderIndex: 3,
      },
      {
        subjectId: subjects[0].id,
        gradeId: grades[0].id,
        name: '일차방정식',
        orderIndex: 4,
      },
      {
        subjectId: subjects[0].id,
        gradeId: grades[0].id,
        name: '기본도형',
        orderIndex: 5,
      },
      {
        subjectId: subjects[0].id,
        gradeId: grades[0].id,
        name: '입체도형',
        orderIndex: 6,
      },
      {
        subjectId: subjects[0].id,
        gradeId: grades[0].id,
        name: '자료의 정리',
        orderIndex: 7,
      },
      // 중2 단원 (7개)
      {
        subjectId: subjects[0].id,
        gradeId: grades[1].id,
        name: '유리수와 순환소수',
        orderIndex: 1,
      },
      {
        subjectId: subjects[0].id,
        gradeId: grades[1].id,
        name: '식의 계산',
        orderIndex: 2,
      },
      {
        subjectId: subjects[0].id,
        gradeId: grades[1].id,
        name: '연립방정식',
        orderIndex: 3,
      },
      {
        subjectId: subjects[0].id,
        gradeId: grades[1].id,
        name: '일차함수',
        orderIndex: 4,
      },
      {
        subjectId: subjects[0].id,
        gradeId: grades[1].id,
        name: '삼각형의 성질',
        orderIndex: 5,
      },
      {
        subjectId: subjects[0].id,
        gradeId: grades[1].id,
        name: '도형의 닮음',
        orderIndex: 6,
      },
      {
        subjectId: subjects[0].id,
        gradeId: grades[1].id,
        name: '확률',
        orderIndex: 7,
      },
      // 중3 단원 (7개)
      {
        subjectId: subjects[0].id,
        gradeId: grades[2].id,
        name: '제곱근과 실수',
        orderIndex: 1,
      },
      {
        subjectId: subjects[0].id,
        gradeId: grades[2].id,
        name: '인수분해',
        orderIndex: 2,
      },
      {
        subjectId: subjects[0].id,
        gradeId: grades[2].id,
        name: '이차방정식',
        orderIndex: 3,
      },
      {
        subjectId: subjects[0].id,
        gradeId: grades[2].id,
        name: '이차함수',
        orderIndex: 4,
      },
      {
        subjectId: subjects[0].id,
        gradeId: grades[2].id,
        name: '삼각비',
        orderIndex: 5,
      },
      {
        subjectId: subjects[0].id,
        gradeId: grades[2].id,
        name: '원의 성질',
        orderIndex: 6,
      },
      {
        subjectId: subjects[0].id,
        gradeId: grades[2].id,
        name: '통계',
        orderIndex: 7,
      },

      // === 영어 단원 ===

      // 영어 중1 단원 (7개)
      {
        subjectId: subjects[1].id,
        gradeId: grades[3].id,
        name: '인사와 소개',
        orderIndex: 1,
      },
      {
        subjectId: subjects[1].id,
        gradeId: grades[3].id,
        name: '일상생활',
        orderIndex: 2,
      },
      {
        subjectId: subjects[1].id,
        gradeId: grades[3].id,
        name: '가족과 친구',
        orderIndex: 3,
      },
      {
        subjectId: subjects[1].id,
        gradeId: grades[3].id,
        name: '학교생활',
        orderIndex: 4,
      },
      {
        subjectId: subjects[1].id,
        gradeId: grades[3].id,
        name: '취미와 여가',
        orderIndex: 5,
      },
      {
        subjectId: subjects[1].id,
        gradeId: grades[3].id,
        name: '음식과 식사',
        orderIndex: 6,
      },
      {
        subjectId: subjects[1].id,
        gradeId: grades[3].id,
        name: '시간과 날짜',
        orderIndex: 7,
      },

      // 영어 중2 단원 (7개)
      {
        subjectId: subjects[1].id,
        gradeId: grades[4].id,
        name: '여행과 교통',
        orderIndex: 1,
      },
      {
        subjectId: subjects[1].id,
        gradeId: grades[4].id,
        name: '쇼핑과 물건',
        orderIndex: 2,
      },
      {
        subjectId: subjects[1].id,
        gradeId: grades[4].id,
        name: '건강과 운동',
        orderIndex: 3,
      },
      {
        subjectId: subjects[1].id,
        gradeId: grades[4].id,
        name: '날씨와 계절',
        orderIndex: 4,
      },
      {
        subjectId: subjects[1].id,
        gradeId: grades[4].id,
        name: '직업과 진로',
        orderIndex: 5,
      },
      {
        subjectId: subjects[1].id,
        gradeId: grades[4].id,
        name: '문화와 축제',
        orderIndex: 6,
      },
      {
        subjectId: subjects[1].id,
        gradeId: grades[4].id,
        name: '환경과 자연',
        orderIndex: 7,
      },

      // 영어 중3 단원 (7개)
      {
        subjectId: subjects[1].id,
        gradeId: grades[5].id,
        name: '사회 문제',
        orderIndex: 1,
      },
      {
        subjectId: subjects[1].id,
        gradeId: grades[5].id,
        name: '과학과 기술',
        orderIndex: 2,
      },
      {
        subjectId: subjects[1].id,
        gradeId: grades[5].id,
        name: '역사와 인물',
        orderIndex: 3,
      },
      {
        subjectId: subjects[1].id,
        gradeId: grades[5].id,
        name: '예술과 음악',
        orderIndex: 4,
      },
      {
        subjectId: subjects[1].id,
        gradeId: grades[5].id,
        name: '스포츠와 게임',
        orderIndex: 5,
      },
      {
        subjectId: subjects[1].id,
        gradeId: grades[5].id,
        name: '미디어와 뉴스',
        orderIndex: 6,
      },
      {
        subjectId: subjects[1].id,
        gradeId: grades[5].id,
        name: '미래와 꿈',
        orderIndex: 7,
      },
    ])
    .returning();

  console.log('✅ Chapters created:', chapters.length);

  // 4. Problems 생성 (21개 단원 × 3문제씩, 총 63문제)
  const problems = await db
    .insert(schema.problems)
    .values([
      // === 중1 단원 (7개 × 3문제 = 21문제) ===

      // 중1-1. 소인수분해 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[0].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: '24를 소인수분해하면?',
        option1: '2 × 12',
        option2: '2² × 6',
        option3: '2³ × 3',
        option4: '3 × 8',
        correctAnswer: '3',
        explanation: '24 = 8 × 3 = 2³ × 3입니다.',
        tags: '소인수분해,기본',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[0].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: '두 수 12와 18의 최대공약수는?',
        option1: '2',
        option2: '3',
        option3: '6',
        option4: '36',
        correctAnswer: '3',
        explanation:
          '12 = 2² × 3, 18 = 2 × 3²이므로 최대공약수는 2 × 3 = 6입니다.',
        tags: '최대공약수,소인수분해',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[0].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: '두 수 48과 72의 최소공배수는?',
        option1: '144',
        option2: '216',
        option3: '288',
        option4: '432',
        correctAnswer: '1',
        explanation:
          '48 = 2⁴ × 3, 72 = 2³ × 3²이므로 최소공배수는 2⁴ × 3² = 144입니다.',
        tags: '최소공배수,소인수분해',
      },

      // 중1-2. 정수와 유리수 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[1].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: '(-8) + 5의 값은?',
        option1: '-13',
        option2: '-3',
        option3: '3',
        option4: '13',
        correctAnswer: '2',
        explanation:
          '절댓값이 큰 -8의 부호를 따라 8 - 5 = 3이고, 부호는 음수이므로 -3입니다.',
        tags: '정수,덧셈',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[1].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: '(-3) × 4 ÷ (-2)의 값은?',
        option1: '-6',
        option2: '6',
        option3: '-24',
        option4: '24',
        correctAnswer: '2',
        explanation: '(-3) × 4 = -12, (-12) ÷ (-2) = 6입니다.',
        tags: '정수,사칙연산',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[1].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: '(-1/2) + (3/4) - (1/3)의 값은?',
        option1: '-1/12',
        option2: '1/12',
        option3: '-5/12',
        option4: '5/12',
        correctAnswer: '1',
        explanation: '통분하면 (-6/12) + (9/12) - (4/12) = -1/12입니다.',
        tags: '유리수,분수계산',
      },

      // 중1-3. 문자와 식 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[2].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: '3x + 2x를 간단히 하면?',
        option1: '5x',
        option2: '5x²',
        option3: '6x',
        option4: 'x⁵',
        correctAnswer: '1',
        explanation: '동류항끼리 모으면 (3 + 2)x = 5x입니다.',
        tags: '문자와식,동류항',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[2].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: '2(x + 3)을 전개하면?',
        option1: '2x + 3',
        option2: '2x + 6',
        option3: 'x + 6',
        option4: '2x + 5',
        correctAnswer: '2',
        explanation: '분배법칙을 사용하면 2x + 6입니다.',
        tags: '문자와식,분배법칙',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[2].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: 'x = 3일 때, 2x² - 5x + 1의 값은?',
        option1: '4',
        option2: '5',
        option3: '6',
        option4: '7',
        correctAnswer: '1',
        explanation: '2(3²) - 5(3) + 1 = 18 - 15 + 1 = 4입니다.',
        tags: '문자와식,식의값',
      },

      // 중1-4. 일차방정식 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[3].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'x + 5 = 12를 풀면?',
        option1: 'x = 5',
        option2: 'x = 7',
        option3: 'x = 12',
        option4: 'x = 17',
        correctAnswer: '2',
        explanation: 'x = 12 - 5 = 7입니다.',
        tags: '일차방정식,기본',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[3].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: '3x + 7 = 19를 풀면?',
        option1: 'x = 3',
        option2: 'x = 4',
        option3: 'x = 5',
        option4: 'x = 6',
        correctAnswer: '2',
        explanation: '3x = 19 - 7 = 12, x = 12 ÷ 3 = 4입니다.',
        tags: '일차방정식,이항',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[3].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: '2(x - 3) = x + 1을 풀면?',
        option1: 'x = 5',
        option2: 'x = 6',
        option3: 'x = 7',
        option4: 'x = 8',
        correctAnswer: '3',
        explanation: '2x - 6 = x + 1, 2x - x = 1 + 6, x = 7입니다.',
        tags: '일차방정식,괄호풀기',
      },

      // 중1-5. 기본도형 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[4].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: '직각은 몇 도인가?',
        option1: '45°',
        option2: '60°',
        option3: '90°',
        option4: '180°',
        correctAnswer: '3',
        explanation: '직각은 90°입니다.',
        tags: '각,기본도형',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[4].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: '맞꼭지각의 크기는?',
        option1: '항상 다르다',
        option2: '항상 같다',
        option3: '합이 180°이다',
        option4: '합이 90°이다',
        correctAnswer: '2',
        explanation: '맞꼭지각은 항상 크기가 같습니다.',
        tags: '각,맞꼭지각',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[4].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: '두 직선이 평행할 때, 엇각의 크기는?',
        option1: '항상 다르다',
        option2: '항상 같다',
        option3: '합이 180°이다',
        option4: '합이 90°이다',
        correctAnswer: '2',
        explanation: '평행선에서 엇각은 항상 크기가 같습니다.',
        tags: '평행선,엇각',
      },

      // 중1-6. 입체도형 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[5].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: '정육면체의 면은 모두 몇 개인가?',
        option1: '4개',
        option2: '6개',
        option3: '8개',
        option4: '12개',
        correctAnswer: '2',
        explanation: '정육면체는 6개의 정사각형 면으로 이루어져 있습니다.',
        tags: '입체도형,정육면체',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[5].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: '한 모서리의 길이가 3 cm인 정육면체의 부피는?',
        option1: '9 cm³',
        option2: '18 cm³',
        option3: '27 cm³',
        option4: '54 cm³',
        correctAnswer: '3',
        explanation: '정육면체의 부피 = 한 모서리³ = 3³ = 27 cm³입니다.',
        tags: '입체도형,부피',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[5].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: '반지름이 3 cm인 구의 겉넓이는? (단, π는 그대로 둔다)',
        option1: '9π cm²',
        option2: '12π cm²',
        option3: '18π cm²',
        option4: '36π cm²',
        correctAnswer: '4',
        explanation: '구의 겉넓이 = 4πr² = 4π × 3² = 36π cm²입니다.',
        tags: '입체도형,구,겉넓이',
      },

      // 중1-7. 자료의 정리 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[6].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: '다음 자료의 평균은? (2, 4, 6, 8)',
        option1: '4',
        option2: '5',
        option3: '6',
        option4: '7',
        correctAnswer: '2',
        explanation: '(2 + 4 + 6 + 8) ÷ 4 = 20 ÷ 4 = 5입니다.',
        tags: '평균,대푯값',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[6].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: '다음 자료의 중앙값은? (1, 3, 5, 7, 9)',
        option1: '3',
        option2: '5',
        option3: '7',
        option4: '9',
        correctAnswer: '2',
        explanation:
          '자료를 순서대로 나열했을 때 가운데 값인 5가 중앙값입니다.',
        tags: '중앙값,대푯값',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[6].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: '다음 자료의 최빈값은? (2, 3, 3, 4, 5, 5, 5, 6)',
        option1: '3',
        option2: '4',
        option3: '5',
        option4: '6',
        correctAnswer: '3',
        explanation: '가장 많이 나타난 값은 5(3회)입니다.',
        tags: '최빈값,대푯값',
      },

      // === 중2 단원 (7개 × 3문제 = 21문제) ===

      // 중2-1. 유리수와 순환소수 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[7].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: '1/4를 소수로 나타내면?',
        option1: '0.2',
        option2: '0.25',
        option3: '0.4',
        option4: '0.5',
        correctAnswer: '2',
        explanation: '1 ÷ 4 = 0.25입니다.',
        tags: '유리수,소수',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[7].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: '0.333...을 기약분수로 나타내면?',
        option1: '1/3',
        option2: '1/4',
        option3: '3/10',
        option4: '33/100',
        correctAnswer: '1',
        explanation: '0.333... = 1/3입니다.',
        tags: '순환소수,분수',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[7].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: '0.272727...을 분수로 나타내면?',
        option1: '27/99',
        option2: '3/11',
        option3: '27/100',
        option4: '1/4',
        correctAnswer: '2',
        explanation: '0.272727... = 27/99 = 3/11입니다.',
        tags: '순환소수,분수변환',
      },

      // 중2-2. 식의 계산 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[8].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: '3x × 2y를 간단히 하면?',
        option1: '5xy',
        option2: '6xy',
        option3: '6x + y',
        option4: '3x + 2y',
        correctAnswer: '2',
        explanation: '3 × 2 × x × y = 6xy입니다.',
        tags: '단항식,곱셈',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[8].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: '(x + 3)(x + 2)를 전개하면?',
        option1: 'x² + 5x + 6',
        option2: 'x² + 6x + 5',
        option3: 'x² + x + 6',
        option4: 'x² + 6x + 6',
        correctAnswer: '1',
        explanation: 'x² + 2x + 3x + 6 = x² + 5x + 6입니다.',
        tags: '다항식,전개',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[8].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: 'x² - 9를 인수분해하면?',
        option1: '(x + 3)(x - 3)',
        option2: '(x - 3)(x - 3)',
        option3: '(x + 3)(x + 3)',
        option4: '인수분해 불가능',
        correctAnswer: '1',
        explanation:
          'a² - b² = (a + b)(a - b) 공식을 사용하면 (x + 3)(x - 3)입니다.',
        tags: '인수분해,곱셈공식',
      },

      // 중2-3. 연립방정식 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[9].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'x + y = 5, x - y = 1을 풀면?',
        option1: 'x = 2, y = 3',
        option2: 'x = 3, y = 2',
        option3: 'x = 4, y = 1',
        option4: 'x = 1, y = 4',
        correctAnswer: '2',
        explanation: '두 식을 더하면 2x = 6, x = 3. y = 5 - 3 = 2입니다.',
        tags: '연립방정식,가감법',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[9].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: '2x + y = 7, x - y = 2를 풀면?',
        option1: 'x = 2, y = 3',
        option2: 'x = 3, y = 1',
        option3: 'x = 3, y = 2',
        option4: 'x = 4, y = 2',
        correctAnswer: '2',
        explanation: '두 식을 더하면 3x = 9, x = 3. y = 7 - 6 = 1입니다.',
        tags: '연립방정식,가감법',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[9].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: '3x + 2y = 12, 2x - y = 1을 풀면?',
        option1: 'x = 1, y = 3',
        option2: 'x = 2, y = 3',
        option3: 'x = 3, y = 2',
        option4: 'x = 2, y = 1',
        correctAnswer: '2',
        explanation:
          '두 번째 식에서 y = 2x - 1을 첫 번째 식에 대입하면 3x + 2(2x - 1) = 12, 7x = 14, x = 2, y = 3입니다.',
        tags: '연립방정식,대입법',
      },

      // 중2-4. 일차함수 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[10].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'y = 2x + 3에서 x = 1일 때 y의 값은?',
        option1: '3',
        option2: '5',
        option3: '7',
        option4: '9',
        correctAnswer: '2',
        explanation: 'y = 2(1) + 3 = 5입니다.',
        tags: '일차함수,함숫값',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[10].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: '일차함수 y = -3x + 6의 기울기는?',
        option1: '-3',
        option2: '3',
        option3: '6',
        option4: '-6',
        correctAnswer: '1',
        explanation: 'y = ax + b에서 기울기는 a = -3입니다.',
        tags: '일차함수,기울기',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[10].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: '점 (1, 4)를 지나고 기울기가 2인 직선의 방정식은?',
        option1: 'y = 2x + 2',
        option2: 'y = 2x + 4',
        option3: 'y = 2x - 2',
        option4: 'y = 2x + 6',
        correctAnswer: '1',
        explanation: 'y - 4 = 2(x - 1)을 정리하면 y = 2x + 2입니다.',
        tags: '일차함수,직선의방정식',
      },

      // 중2-5. 삼각형의 성질 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[11].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: '삼각형의 내각의 합은?',
        option1: '90°',
        option2: '180°',
        option3: '270°',
        option4: '360°',
        correctAnswer: '2',
        explanation: '모든 삼각형의 세 내각의 합은 180°입니다.',
        tags: '삼각형,내각의합',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[11].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText:
          '이등변삼각형의 두 밑각의 크기가 같을 때, 한 밑각이 50°이면 꼭지각은?',
        option1: '50°',
        option2: '60°',
        option3: '70°',
        option4: '80°',
        correctAnswer: '4',
        explanation: '꼭지각 = 180° - 50° - 50° = 80°입니다.',
        tags: '이등변삼각형,내각',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[11].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText:
          '직각삼각형에서 빗변의 길이가 5 cm, 한 변의 길이가 3 cm일 때 나머지 한 변의 길이는?',
        option1: '2 cm',
        option2: '3 cm',
        option3: '4 cm',
        option4: '5 cm',
        correctAnswer: '3',
        explanation:
          '피타고라스 정리: 5² = 3² + x², 25 = 9 + x², x² = 16, x = 4 cm입니다.',
        tags: '직각삼각형,피타고라스정리',
      },

      // 중2-6. 도형의 닮음 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[12].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: '닮음비가 1:2인 두 도형에서 넓이의 비는?',
        option1: '1:2',
        option2: '1:4',
        option3: '2:4',
        option4: '1:8',
        correctAnswer: '2',
        explanation: '넓이의 비는 닮음비의 제곱이므로 1²:2² = 1:4입니다.',
        tags: '닮음,넓이의비',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[12].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: '닮음비가 2:3인 두 직육면체의 부피의 비는?',
        option1: '2:3',
        option2: '4:9',
        option3: '8:27',
        option4: '16:81',
        correctAnswer: '3',
        explanation: '부피의 비는 닮음비의 세제곱이므로 2³:3³ = 8:27입니다.',
        tags: '닮음,부피의비',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[12].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText:
          '한 변의 길이가 6 cm인 정사각형과 닮음인 정사각형의 한 변의 길이가 9 cm일 때, 넓이의 비는?',
        option1: '2:3',
        option2: '3:4',
        option3: '4:9',
        option4: '36:81',
        correctAnswer: '3',
        explanation: '닮음비 = 6:9 = 2:3, 넓이의 비 = 2²:3² = 4:9입니다.',
        tags: '닮음,정사각형,넓이',
      },

      // 중2-7. 확률 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[13].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: '주사위 1개를 던질 때 3이 나올 확률은?',
        option1: '1/2',
        option2: '1/3',
        option3: '1/4',
        option4: '1/6',
        correctAnswer: '4',
        explanation:
          '3이 나오는 경우의 수는 1, 전체 경우의 수는 6이므로 1/6입니다.',
        tags: '확률,기본',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[13].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: '동전 2개를 던질 때 모두 앞면이 나올 확률은?',
        option1: '1/2',
        option2: '1/3',
        option3: '1/4',
        option4: '1/8',
        correctAnswer: '3',
        explanation:
          '전체 경우의 수는 4(앞앞, 앞뒤, 뒤앞, 뒤뒤), 모두 앞면인 경우는 1이므로 1/4입니다.',
        tags: '확률,여러번시행',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[13].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText:
          '1부터 10까지의 자연수 중에서 임의로 하나를 뽑을 때 소수일 확률은?',
        option1: '2/5',
        option2: '3/10',
        option3: '1/2',
        option4: '3/5',
        correctAnswer: '1',
        explanation: '소수는 2, 3, 5, 7로 4개이므로 4/10 = 2/5입니다.',
        tags: '확률,소수',
      },

      // === 중3 단원 (7개 × 3문제 = 21문제) ===

      // 중3-1. 제곱근과 실수 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[14].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: '√16의 값은?',
        option1: '2',
        option2: '4',
        option3: '8',
        option4: '16',
        correctAnswer: '2',
        explanation: '4² = 16이므로 √16 = 4입니다.',
        tags: '제곱근,기본',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[14].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: '√18 - √8을 간단히 하면?',
        option1: '√2',
        option2: '2√2',
        option3: '√10',
        option4: '3√2',
        correctAnswer: '1',
        explanation: '√18 = 3√2, √8 = 2√2이므로 3√2 - 2√2 = √2입니다.',
        tags: '제곱근,간단히하기',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[14].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: '√2 × √8을 간단히 하면?',
        option1: '2',
        option2: '4',
        option3: '√16',
        option4: '8',
        correctAnswer: '2',
        explanation: '√2 × √8 = √16 = 4입니다.',
        tags: '제곱근,곱셈',
      },

      // 중3-2. 인수분해 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[15].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'x² - 4를 인수분해하면?',
        option1: '(x + 2)(x - 2)',
        option2: '(x - 2)(x - 2)',
        option3: '(x + 4)(x - 1)',
        option4: '인수분해 불가능',
        correctAnswer: '1',
        explanation:
          'a² - b² = (a + b)(a - b) 공식을 사용하면 (x + 2)(x - 2)입니다.',
        tags: '인수분해,차의제곱',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[15].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'x² + 6x + 9를 인수분해하면?',
        option1: '(x + 3)²',
        option2: '(x + 9)(x + 1)',
        option3: '(x + 3)(x + 3)',
        option4: '(x - 3)²',
        correctAnswer: '1',
        explanation: 'a² + 2ab + b² = (a + b)² 공식을 사용하면 (x + 3)²입니다.',
        tags: '인수분해,완전제곱식',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[15].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: 'x² + 5x + 6을 인수분해하면?',
        option1: '(x + 1)(x + 6)',
        option2: '(x + 2)(x + 3)',
        option3: '(x + 5)(x + 1)',
        option4: '인수분해 불가능',
        correctAnswer: '2',
        explanation:
          '합이 5, 곱이 6인 두 수는 2와 3이므로 (x + 2)(x + 3)입니다.',
        tags: '인수분해,이차식',
      },

      // 중3-3. 이차방정식 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[16].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'x² = 9의 해는?',
        option1: 'x = 3',
        option2: 'x = -3',
        option3: 'x = ±3',
        option4: 'x = 9',
        correctAnswer: '3',
        explanation: 'x = ±√9 = ±3입니다.',
        tags: '이차방정식,기본',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[16].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'x² - 5x + 6 = 0의 해는?',
        option1: 'x = 2, 3',
        option2: 'x = -2, -3',
        option3: 'x = 1, 6',
        option4: 'x = -1, -6',
        correctAnswer: '1',
        explanation:
          '인수분해하면 (x - 2)(x - 3) = 0이므로 x = 2 또는 x = 3입니다.',
        tags: '이차방정식,인수분해',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[16].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: 'x² + 4x - 5 = 0의 해는?',
        option1: 'x = 1, -5',
        option2: 'x = -1, 5',
        option3: 'x = 1, 5',
        option4: 'x = -1, -5',
        correctAnswer: '1',
        explanation:
          '인수분해하면 (x - 1)(x + 5) = 0이므로 x = 1 또는 x = -5입니다.',
        tags: '이차방정식,인수분해',
      },

      // 중3-4. 이차함수 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[17].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'y = x²의 그래프에서 x = 2일 때 y의 값은?',
        option1: '2',
        option2: '4',
        option3: '8',
        option4: '16',
        correctAnswer: '2',
        explanation: 'y = 2² = 4입니다.',
        tags: '이차함수,함숫값',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[17].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'y = 2x²의 그래프는 y = x²의 그래프와 비교할 때?',
        option1: 'x축 방향으로 2배 확대',
        option2: 'y축 방향으로 2배 확대',
        option3: 'x축 방향으로 1/2배 축소',
        option4: 'y축 방향으로 1/2배 축소',
        correctAnswer: '2',
        explanation: 'y = ax²에서 |a| > 1이면 y축 방향으로 확대됩니다.',
        tags: '이차함수,그래프변환',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[17].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: 'y = x² - 4x + 3의 그래프의 꼭짓점의 좌표는?',
        option1: '(2, -1)',
        option2: '(-2, -1)',
        option3: '(2, 1)',
        option4: '(-2, 1)',
        correctAnswer: '1',
        explanation: 'y = (x - 2)² - 1로 변형하면 꼭짓점은 (2, -1)입니다.',
        tags: '이차함수,꼭짓점',
      },

      // 중3-5. 삼각비 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[18].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'sin 30°의 값은?',
        option1: '1/2',
        option2: '√2/2',
        option3: '√3/2',
        option4: '1',
        correctAnswer: '1',
        explanation: 'sin 30° = 1/2입니다.',
        tags: '삼각비,특수각',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[18].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'cos 60°의 값은?',
        option1: '1/2',
        option2: '√2/2',
        option3: '√3/2',
        option4: '1',
        correctAnswer: '1',
        explanation: 'cos 60° = 1/2입니다.',
        tags: '삼각비,특수각',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[18].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText:
          '직각삼각형에서 빗변의 길이가 10, 한 예각의 크기가 30°일 때 이 각의 대변의 길이는?',
        option1: '5',
        option2: '5√2',
        option3: '5√3',
        option4: '10',
        correctAnswer: '1',
        explanation: '대변 = 빗변 × sin 30° = 10 × 1/2 = 5입니다.',
        tags: '삼각비,활용',
      },

      // 중3-6. 원의 성질 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[19].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: '반지름이 5 cm인 원의 넓이는? (단, π는 그대로 둔다)',
        option1: '5π cm²',
        option2: '10π cm²',
        option3: '25π cm²',
        option4: '50π cm²',
        correctAnswer: '3',
        explanation: '원의 넓이 = πr² = π × 5² = 25π cm²입니다.',
        tags: '원,넓이',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[19].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText:
          '반지름이 6 cm인 원에서 중심각이 60°인 부채꼴의 호의 길이는? (단, π는 그대로 둔다)',
        option1: 'π cm',
        option2: '2π cm',
        option3: '3π cm',
        option4: '6π cm',
        correctAnswer: '2',
        explanation:
          '호의 길이 = 2πr × (중심각/360°) = 2π × 6 × (60/360) = 2π cm입니다.',
        tags: '원,부채꼴,호의길이',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[19].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: '원에 내접하는 사각형에서 대각의 크기의 합은?',
        option1: '90°',
        option2: '120°',
        option3: '180°',
        option4: '360°',
        correctAnswer: '3',
        explanation: '원에 내접하는 사각형의 대각의 크기의 합은 180°입니다.',
        tags: '원,내접사각형',
      },

      // 중3-7. 통계 (3문제: 초/중/상)
      {
        subjectId: subjects[0].id,
        chapterId: chapters[20].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: '다음 자료의 평균은? (10, 20, 30, 40)',
        option1: '20',
        option2: '25',
        option3: '30',
        option4: '35',
        correctAnswer: '2',
        explanation: '(10 + 20 + 30 + 40) ÷ 4 = 100 ÷ 4 = 25입니다.',
        tags: '평균,통계',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[20].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: '다음 자료의 분산은? (2, 4, 6, 8)',
        option1: '3',
        option2: '4',
        option3: '5',
        option4: '6',
        correctAnswer: '3',
        explanation:
          '평균은 5. 분산 = [(2-5)² + (4-5)² + (6-5)² + (8-5)²] / 4 = 20 / 4 = 5입니다.',
        tags: '분산,통계',
      },
      {
        subjectId: subjects[0].id,
        chapterId: chapters[20].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: '다음 자료의 표준편차는? (1, 3, 5, 7, 9)',
        option1: '2',
        option2: '4',
        option3: '√8',
        option4: '√10',
        correctAnswer: '3',
        explanation:
          '평균은 5. 분산 = [(1-5)² + (3-5)² + (5-5)² + (7-5)² + (9-5)²] / 5 = 40/5 = 8, 표준편차 = √8입니다.',
        tags: '표준편차,분산,통계',
      },

      // === 영어 문제 (21개 단원 × 3문제 = 63문제) ===

      // 영어 중1-1. 인사와 소개 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[21].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText:
          "A: Hi, I'm Tom. ___ to meet you.\nB: Nice to meet you, too.",
        option1: 'Nice',
        option2: 'Good',
        option3: 'Happy',
        option4: 'Glad',
        correctAnswer: '1',
        explanation: '"Nice to meet you"는 처음 만났을 때 사용하는 인사입니다.',
        tags: '인사,소개,관용표현',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[21].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'My name ___ Sarah and I ___ from Canada.',
        option1: 'is, am',
        option2: 'am, is',
        option3: 'are, am',
        option4: 'is, are',
        correctAnswer: '1',
        explanation:
          '주어가 "My name"(3인칭 단수)일 때는 is, "I"일 때는 am을 사용합니다.',
        tags: 'be동사,자기소개',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[21].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText:
          'Choose the correct response:\nA: How do you spell your name?\nB: ___',
        option1: "I'm fine, thank you.",
        option2: "It's J-O-H-N.",
        option3: "I'm 13 years old.",
        option4: 'I live in Seoul.',
        correctAnswer: '2',
        explanation:
          '"How do you spell~?"는 철자를 묻는 질문으로, 알파벳을 하나씩 말해야 합니다.',
        tags: '철자,질문응답',
      },

      // 영어 중1-2. 일상생활 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[22].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: "I ___ up at 7 o'clock every morning.",
        option1: 'get',
        option2: 'gets',
        option3: 'getting',
        option4: 'got',
        correctAnswer: '1',
        explanation: '주어가 "I"이므로 동사원형 "get"을 사용합니다.',
        tags: '일상생활,현재시제',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[22].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'She always ___ her homework after dinner.',
        option1: 'do',
        option2: 'does',
        option3: 'doing',
        option4: 'did',
        correctAnswer: '2',
        explanation:
          '3인칭 단수 주어(She)이고 현재시제이므로 "does"를 사용합니다.',
        tags: '3인칭단수,현재시제',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[22].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText:
          'How often do you brush your teeth?\n- I brush my teeth ___.',
        option1: 'yesterday',
        option2: 'next week',
        option3: 'twice a day',
        option4: 'two hours',
        correctAnswer: '3',
        explanation:
          '"How often"은 빈도를 묻는 질문이므로 "twice a day"(하루에 두 번)가 적절합니다.',
        tags: '빈도부사,일상습관',
      },

      // 영어 중1-3. 가족과 친구 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[23].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'This is ___ sister. Her name is Jenny.',
        option1: 'I',
        option2: 'my',
        option3: 'me',
        option4: 'mine',
        correctAnswer: '2',
        explanation: '명사(sister) 앞에는 소유격(my)을 사용합니다.',
        tags: '소유격,가족',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[23].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'My brother ___ taller than me.',
        option1: 'am',
        option2: 'is',
        option3: 'are',
        option4: 'be',
        correctAnswer: '2',
        explanation: '주어가 "My brother"(3인칭 단수)이므로 "is"를 사용합니다.',
        tags: 'be동사,비교급',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[23].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText:
          'There ___ four people in my family: my parents, my sister, and me.',
        option1: 'is',
        option2: 'am',
        option3: 'are',
        option4: 'be',
        correctAnswer: '3',
        explanation: '"four people"(복수)이므로 "are"를 사용합니다.',
        tags: 'There구문,복수',
      },

      // 영어 중1-4. 학교생활 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[24].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'I go ___ school by bus.',
        option1: 'at',
        option2: 'to',
        option3: 'in',
        option4: 'on',
        correctAnswer: '2',
        explanation: '"go to + 장소"는 ~에 가다는 의미입니다.',
        tags: '전치사,학교생활',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[24].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'What subject do you like ___?\n- I like math best.',
        option1: 'good',
        option2: 'well',
        option3: 'better',
        option4: 'best',
        correctAnswer: '4',
        explanation: '"가장 좋아하는"이라는 의미로 최상급 "best"를 사용합니다.',
        tags: '최상급,과목',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[24].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: 'My English teacher ___ us a lot of homework every day.',
        option1: 'give',
        option2: 'gives',
        option3: 'giving',
        option4: 'gave',
        correctAnswer: '2',
        explanation:
          '3인칭 단수 주어(teacher)이고 현재시제이므로 "gives"를 사용합니다.',
        tags: '3인칭단수,수여동사',
      },

      // 영어 중1-5. 취미와 여가 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[25].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'I like ___ music in my free time.',
        option1: 'listen',
        option2: 'listening',
        option3: 'listens',
        option4: 'listened',
        correctAnswer: '2',
        explanation: '"like + -ing"는 ~하는 것을 좋아한다는 의미입니다.',
        tags: '동명사,취미',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[25].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'She is good at ___ the piano.',
        option1: 'play',
        option2: 'plays',
        option3: 'playing',
        option4: 'played',
        correctAnswer: '3',
        explanation: '"be good at + -ing"는 ~을 잘한다는 의미입니다.',
        tags: '전치사,동명사',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[25].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: 'Would you like ___ basketball with me this afternoon?',
        option1: 'play',
        option2: 'to play',
        option3: 'playing',
        option4: 'played',
        correctAnswer: '2',
        explanation:
          '"Would you like to + 동사원형"은 ~하시겠습니까?라는 정중한 제안입니다.',
        tags: 'to부정사,제안',
      },

      // 영어 중1-6. 음식과 식사 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[26].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'I want ___ apple.',
        option1: 'a',
        option2: 'an',
        option3: 'the',
        option4: '(관사 없음)',
        correctAnswer: '2',
        explanation: '"apple"은 모음으로 시작하므로 "an"을 사용합니다.',
        tags: '관사,음식',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[26].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'There ___ some milk in the fridge.',
        option1: 'is',
        option2: 'are',
        option3: 'am',
        option4: 'be',
        correctAnswer: '1',
        explanation:
          '"milk"는 셀 수 없는 명사이므로 단수 취급하여 "is"를 사용합니다.',
        tags: 'There구문,불가산명사',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[26].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: 'How ___ water do you drink every day?',
        option1: 'many',
        option2: 'much',
        option3: 'often',
        option4: 'long',
        correctAnswer: '2',
        explanation: '"water"는 셀 수 없는 명사이므로 "How much"를 사용합니다.',
        tags: '의문사,불가산명사',
      },

      // 영어 중1-7. 시간과 날짜 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[27].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: "What time is it?\n- It's ___ o'clock.",
        option1: 'three',
        option2: 'third',
        option3: 'the three',
        option4: "three's",
        correctAnswer: '1',
        explanation: '시간을 말할 때는 기수(three)를 사용합니다.',
        tags: '시간,숫자',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[27].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'My birthday is ___ May 15th.',
        option1: 'at',
        option2: 'in',
        option3: 'on',
        option4: 'to',
        correctAnswer: '3',
        explanation: '특정 날짜 앞에는 전치사 "on"을 사용합니다.',
        tags: '전치사,날짜',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[27].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: "The movie starts ___ 7:30 p.m. Don't be late!",
        option1: 'in',
        option2: 'on',
        option3: 'at',
        option4: 'for',
        correctAnswer: '3',
        explanation: '구체적인 시각 앞에는 전치사 "at"을 사용합니다.',
        tags: '전치사,시각',
      },

      // 영어 중2-1. 여행과 교통 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[28].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'I ___ to Busan last summer.',
        option1: 'go',
        option2: 'goes',
        option3: 'went',
        option4: 'going',
        correctAnswer: '3',
        explanation: '"last summer"는 과거이므로 과거형 "went"를 사용합니다.',
        tags: '과거시제,여행',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[28].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'How long does it ___ to get to the airport?',
        option1: 'take',
        option2: 'takes',
        option3: 'taking',
        option4: 'took',
        correctAnswer: '1',
        explanation: '조동사(does) 뒤에는 동사원형을 사용합니다.',
        tags: '소요시간,의문문',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[28].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: 'I have ___ been to Europe. I want to go there someday.',
        option1: 'ever',
        option2: 'never',
        option3: 'already',
        option4: 'yet',
        correctAnswer: '2',
        explanation: '"never"는 한 번도 ~한 적이 없다는 의미입니다.',
        tags: '현재완료,부정',
      },

      // 영어 중2-2. 쇼핑과 물건 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[29].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: "How ___ is this shirt?\n- It's 30 dollars.",
        option1: 'many',
        option2: 'much',
        option3: 'long',
        option4: 'often',
        correctAnswer: '2',
        explanation: '가격을 물을 때는 "How much"를 사용합니다.',
        tags: '가격,쇼핑',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[29].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'Can I try ___ this jacket?',
        option1: 'on',
        option2: 'in',
        option3: 'at',
        option4: 'to',
        correctAnswer: '1',
        explanation: '"try on"은 (옷을) 입어보다는 의미의 구동사입니다.',
        tags: '구동사,쇼핑',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[29].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: 'This bag is ___ expensive than that one.',
        option1: 'more',
        option2: 'most',
        option3: 'much',
        option4: 'many',
        correctAnswer: '1',
        explanation:
          '"expensive"는 긴 형용사이므로 "more + 형용사"로 비교급을 만듭니다.',
        tags: '비교급,쇼핑',
      },

      // 영어 중2-3. 건강과 운동 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[30].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'You should ___ more water.',
        option1: 'drink',
        option2: 'drinks',
        option3: 'drinking',
        option4: 'drank',
        correctAnswer: '1',
        explanation: '조동사(should) 뒤에는 동사원형을 사용합니다.',
        tags: '조동사,건강',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[30].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'I feel ___. I think I have a cold.',
        option1: 'sick',
        option2: 'sickly',
        option3: 'sickness',
        option4: 'sicked',
        correctAnswer: '1',
        explanation: '"feel"은 감각동사로 뒤에 형용사 "sick"가 옵니다.',
        tags: '감각동사,건강',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[30].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: 'Exercise is important ___ your health.',
        option1: 'to',
        option2: 'for',
        option3: 'at',
        option4: 'in',
        correctAnswer: '2',
        explanation: '"be important for"는 ~에 중요하다는 의미입니다.',
        tags: '전치사,건강',
      },

      // 영어 중2-4. 날씨와 계절 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[31].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'It ___ raining outside now.',
        option1: 'is',
        option2: 'are',
        option3: 'am',
        option4: 'be',
        correctAnswer: '1',
        explanation:
          '날씨를 나타낼 때는 주어로 "It"을 사용하고 "is"와 함께 씁니다.',
        tags: '날씨,현재진행형',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[31].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: "What's the weather ___ today?",
        option1: 'look',
        option2: 'like',
        option3: 'as',
        option4: 'for',
        correctAnswer: '2',
        explanation:
          '"What\'s the weather like?"는 날씨가 어떠냐고 묻는 표현입니다.',
        tags: '날씨,관용표현',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[31].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: 'If it ___ tomorrow, we will stay home.',
        option1: 'rain',
        option2: 'rains',
        option3: 'will rain',
        option4: 'rained',
        correctAnswer: '2',
        explanation:
          '조건절(if절)에서는 미래를 나타내도 현재시제를 사용합니다.',
        tags: '조건문,날씨',
      },

      // 영어 중2-5. 직업과 진로 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[32].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'What do you want to ___?\n- I want to be a teacher.',
        option1: 'do',
        option2: 'be',
        option3: 'have',
        option4: 'make',
        correctAnswer: '2',
        explanation: '직업을 나타낼 때는 "be + 직업"을 사용합니다.',
        tags: '직업,미래',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[32].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'My father works ___ a hospital. He is a doctor.',
        option1: 'in',
        option2: 'at',
        option3: 'on',
        option4: 'to',
        correctAnswer: '2',
        explanation: '직장이나 근무지를 나타낼 때는 "work at"을 사용합니다.',
        tags: '전치사,직업',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[32].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: 'To become a scientist, you need ___ hard.',
        option1: 'study',
        option2: 'to study',
        option3: 'studying',
        option4: 'studied',
        correctAnswer: '2',
        explanation: '"need to + 동사원형"은 ~할 필요가 있다는 의미입니다.',
        tags: 'to부정사,진로',
      },

      // 영어 중2-6. 문화와 축제 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[33].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'Halloween is celebrated ___ October 31st.',
        option1: 'at',
        option2: 'in',
        option3: 'on',
        option4: 'for',
        correctAnswer: '3',
        explanation: '특정 날짜 앞에는 전치사 "on"을 사용합니다.',
        tags: '전치사,축제',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[33].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'People ___ traditional clothes during the festival.',
        option1: 'wear',
        option2: 'wears',
        option3: 'wearing',
        option4: 'wore',
        correctAnswer: '1',
        explanation: '주어 "People"(복수)이므로 동사원형 "wear"를 사용합니다.',
        tags: '주어-동사일치,문화',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[33].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: 'This festival ___ every year since 1950.',
        option1: 'holds',
        option2: 'held',
        option3: 'has held',
        option4: 'has been held',
        correctAnswer: '4',
        explanation:
          '"축제가 열리다"는 수동태이고, "since 1950"이므로 현재완료(has been held)를 사용합니다.',
        tags: '수동태,현재완료',
      },

      // 영어 중2-7. 환경과 자연 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[34].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'We should ___ the environment.',
        option1: 'protect',
        option2: 'protects',
        option3: 'protecting',
        option4: 'protected',
        correctAnswer: '1',
        explanation: '조동사(should) 뒤에는 동사원형을 사용합니다.',
        tags: '조동사,환경',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[34].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'Plastic bags are bad ___ the ocean.',
        option1: 'to',
        option2: 'at',
        option3: 'for',
        option4: 'in',
        correctAnswer: '3',
        explanation: '"be bad for"는 ~에 나쁘다는 의미입니다.',
        tags: '전치사,환경',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[34].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText:
          "If we don't stop ___ fossil fuels, global warming will get worse.",
        option1: 'use',
        option2: 'to use',
        option3: 'using',
        option4: 'used',
        correctAnswer: '3',
        explanation: '"stop + -ing"는 ~하는 것을 멈추다는 의미입니다.',
        tags: '동명사,환경',
      },

      // 영어 중3-1. 사회 문제 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[35].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'Poverty is a serious ___ in many countries.',
        option1: 'problem',
        option2: 'problems',
        option3: 'problematic',
        option4: 'probably',
        correctAnswer: '1',
        explanation: '관사 "a" 뒤에 단수명사 "problem"이 옵니다.',
        tags: '명사,사회문제',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[35].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'Everyone has the right ___ education.',
        option1: 'for',
        option2: 'to',
        option3: 'at',
        option4: 'in',
        correctAnswer: '2',
        explanation: '"the right to"는 ~할 권리라는 의미입니다.',
        tags: '전치사,권리',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[35].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText:
          'The government should ___ more laws to protect children.',
        option1: 'make',
        option2: 'makes',
        option3: 'making',
        option4: 'made',
        correctAnswer: '1',
        explanation: '조동사(should) 뒤에는 동사원형을 사용합니다.',
        tags: '조동사,법',
      },

      // 영어 중3-2. 과학과 기술 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[36].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'Smartphones ___ invented in the 1990s.',
        option1: 'are',
        option2: 'is',
        option3: 'was',
        option4: 'were',
        correctAnswer: '4',
        explanation:
          '주어가 복수(Smartphones)이고 과거이므로 "were"를 사용합니다.',
        tags: '수동태,과거시제',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[36].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'Technology has ___ our lives easier.',
        option1: 'make',
        option2: 'makes',
        option3: 'made',
        option4: 'making',
        correctAnswer: '3',
        explanation: '현재완료(has + 과거분사)이므로 "made"를 사용합니다.',
        tags: '현재완료,기술',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[36].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: 'AI will be used ___ various fields in the future.',
        option1: 'at',
        option2: 'in',
        option3: 'on',
        option4: 'for',
        correctAnswer: '2',
        explanation: '"in various fields"는 다양한 분야에서라는 의미입니다.',
        tags: '전치사,미래',
      },

      // 영어 중3-3. 역사와 인물 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[37].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText:
          'Abraham Lincoln ___ the 16th president of the United States.',
        option1: 'is',
        option2: 'was',
        option3: 'are',
        option4: 'were',
        correctAnswer: '2',
        explanation: '링컨은 과거의 인물이므로 과거형 "was"를 사용합니다.',
        tags: '과거시제,역사',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[37].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'She is known ___ her contributions to science.',
        option1: 'for',
        option2: 'as',
        option3: 'to',
        option4: 'at',
        correctAnswer: '1',
        explanation: '"be known for"는 ~로 알려져 있다는 의미입니다.',
        tags: '전치사,인물',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[37].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText:
          'If he ___ lived longer, he would have written more books.',
        option1: 'has',
        option2: 'have',
        option3: 'had',
        option4: 'having',
        correctAnswer: '3',
        explanation: '가정법 과거완료로, if절에 "had + 과거분사"를 사용합니다.',
        tags: '가정법,역사',
      },

      // 영어 중3-4. 예술과 음악 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[38].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'This painting was ___ by Picasso.',
        option1: 'paint',
        option2: 'paints',
        option3: 'painted',
        option4: 'painting',
        correctAnswer: '3',
        explanation: '수동태 "be + 과거분사"이므로 "painted"를 사용합니다.',
        tags: '수동태,예술',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[38].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'Classical music ___ me feel relaxed.',
        option1: 'make',
        option2: 'makes',
        option3: 'making',
        option4: 'made',
        correctAnswer: '2',
        explanation:
          '주어 "music"(3인칭 단수)이고 현재시제이므로 "makes"를 사용합니다.',
        tags: '사역동사,음악',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[38].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText:
          'The concert hall is ___ beautiful that I want to visit again.',
        option1: 'so',
        option2: 'such',
        option3: 'very',
        option4: 'too',
        correctAnswer: '1',
        explanation: '"so + 형용사 + that"은 너무 ~해서 ...하다는 의미입니다.',
        tags: '구문,예술',
      },

      // 영어 중3-5. 스포츠와 게임 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[39].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'I enjoy ___ soccer on weekends.',
        option1: 'play',
        option2: 'plays',
        option3: 'playing',
        option4: 'played',
        correctAnswer: '3',
        explanation: '"enjoy + -ing"는 ~하는 것을 즐기다는 의미입니다.',
        tags: '동명사,스포츠',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[39].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'Our team ___ the championship last year.',
        option1: 'win',
        option2: 'wins',
        option3: 'won',
        option4: 'winning',
        correctAnswer: '3',
        explanation: '"last year"는 과거이므로 과거형 "won"을 사용합니다.',
        tags: '과거시제,스포츠',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[39].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText:
          'He practices ___ hard that he became a professional player.',
        option1: 'so',
        option2: 'such',
        option3: 'very',
        option4: 'too',
        correctAnswer: '1',
        explanation:
          '"so + 부사 + that"은 너무 ~하게 해서 ...하다는 의미입니다.',
        tags: '구문,스포츠',
      },

      // 영어 중3-6. 미디어와 뉴스 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[40].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'The news ___ broadcast every evening.',
        option1: 'is',
        option2: 'are',
        option3: 'am',
        option4: 'be',
        correctAnswer: '1',
        explanation: '"news"는 단수 취급하므로 "is"를 사용합니다.',
        tags: '주어-동사일치,미디어',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[40].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'Social media ___ changed the way we communicate.',
        option1: 'have',
        option2: 'has',
        option3: 'had',
        option4: 'having',
        correctAnswer: '2',
        explanation:
          '"Social media"는 단수 취급하고 현재완료이므로 "has"를 사용합니다.',
        tags: '현재완료,미디어',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[40].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: 'We should be careful about ___ fake news online.',
        option1: 'spread',
        option2: 'spreads',
        option3: 'spreading',
        option4: 'to spread',
        correctAnswer: '3',
        explanation: '"about + -ing"는 ~하는 것에 대해라는 의미입니다.',
        tags: '전치사,동명사',
      },

      // 영어 중3-7. 미래와 꿈 (3문제: 초/중/상)
      {
        subjectId: subjects[1].id,
        chapterId: chapters[41].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        questionText: 'I ___ travel around the world someday.',
        option1: 'will',
        option2: 'am',
        option3: 'do',
        option4: 'can',
        correctAnswer: '1',
        explanation: '미래의 계획을 나타낼 때 "will"을 사용합니다.',
        tags: '미래시제,꿈',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[41].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        questionText: 'My dream is ___ become a doctor.',
        option1: 'for',
        option2: 'to',
        option3: 'at',
        option4: 'in',
        correctAnswer: '2',
        explanation:
          '"My dream is to + 동사원형"은 내 꿈은 ~하는 것이다라는 의미입니다.',
        tags: 'to부정사,꿈',
      },
      {
        subjectId: subjects[1].id,
        chapterId: chapters[41].id,
        questionType: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        questionText: 'By 2050, people ___ living on Mars.',
        option1: 'will',
        option2: 'will be',
        option3: 'are',
        option4: 'were',
        correctAnswer: '2',
        explanation:
          '미래 특정 시점에 진행 중인 동작은 "will be + -ing"로 나타냅니다.',
        tags: '미래진행형,예측',
      },
    ])
    .returning();

  console.log('✅ Problems created:', problems.length);

  // 5. Test Sets 생성
  const testSets = await db
    .insert(schema.testSets)
    .values([
      {
        title: '중1 수학 중간고사',
        description: '중1 수학 수와 연산, 문자와 식 단원',
        subjectId: subjects[0].id,
        gradeId: grades[0].id,
        testType: 'MIDTERM',
        totalQuestions: 4,
        timeLimit: 30,
      },
      {
        title: '중2 수학 기말고사',
        description: '중2 수학 전체 범위',
        subjectId: subjects[0].id,
        gradeId: grades[1].id,
        testType: 'FINAL',
        totalQuestions: 5,
        timeLimit: 40,
      },
      {
        title: '중3 수학 모의고사',
        description: '중3 수학 이차방정식, 함수 단원',
        subjectId: subjects[0].id,
        gradeId: grades[2].id,
        testType: 'MOCK',
        totalQuestions: 4,
        timeLimit: 30,
      },
    ])
    .returning();

  console.log('✅ Test Sets created:', testSets.length);

  // 6. Test Set Problems 연결 (N:M)
  await db.insert(schema.testSetProblems).values([
    // 중1 중간고사 (수와 연산, 문자와 식)
    {
      testSetId: testSets[0].id,
      problemId: problems[0].id, // 중1-수와연산-1
      orderIndex: 1,
      score: 5,
    },
    {
      testSetId: testSets[0].id,
      problemId: problems[1].id, // 중1-수와연산-2
      orderIndex: 2,
      score: 5,
    },
    {
      testSetId: testSets[0].id,
      problemId: problems[2].id, // 중1-문자와식-1
      orderIndex: 3,
      score: 5,
    },
    {
      testSetId: testSets[0].id,
      problemId: problems[3].id, // 중1-문자와식-2
      orderIndex: 4,
      score: 5,
    },
    // 중2 기말고사 (각 단원에서 1문제씩)
    {
      testSetId: testSets[1].id,
      problemId: problems[10].id, // 중2-수와연산-1
      orderIndex: 1,
      score: 6,
    },
    {
      testSetId: testSets[1].id,
      problemId: problems[12].id, // 중2-식의계산-1
      orderIndex: 2,
      score: 6,
    },
    {
      testSetId: testSets[1].id,
      problemId: problems[14].id, // 중2-함수-1
      orderIndex: 3,
      score: 6,
    },
    {
      testSetId: testSets[1].id,
      problemId: problems[16].id, // 중2-기하-1
      orderIndex: 4,
      score: 6,
    },
    {
      testSetId: testSets[1].id,
      problemId: problems[18].id, // 중2-확률과통계-1
      orderIndex: 5,
      score: 6,
    },
    // 중3 모의고사 (이차방정식, 함수)
    {
      testSetId: testSets[2].id,
      problemId: problems[24].id, // 중3-이차방정식-1
      orderIndex: 1,
      score: 7,
    },
    {
      testSetId: testSets[2].id,
      problemId: problems[25].id, // 중3-이차방정식-2
      orderIndex: 2,
      score: 7,
    },
    {
      testSetId: testSets[2].id,
      problemId: problems[26].id, // 중3-함수-1
      orderIndex: 3,
      score: 8,
    },
    {
      testSetId: testSets[2].id,
      problemId: problems[27].id, // 중3-함수-2
      orderIndex: 4,
      score: 8,
    },
  ]);

  console.log('✅ Test Set Problems connected');
  console.log('🎉 Seed completed!');

  await pool.end();
}

seed().catch((error) => {
  console.error('❌ Seed failed:', error);
  process.exit(1);
});
